connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: ENV["db_user"]
  password: ENV["db_pass"]

development:
  <<: *connection
  database: workshops_development

test: &test
  <<: *connection
  database: workshops_test