Site.create name: 'Onet', site_color: '#FFA900', favurl: 'http://www.onet.pl/favicon.ico' unless Site.find_by(name: 'Onet')
Site.create name: 'Interia', site_color: '#1C3F6F', favurl: 'http://www.interia.pl/favicon.ico' unless Site.find_by(name: 'Interia')
Site.create name: 'TVN24', site_color: '#00599F', favurl: 'http://www.tvn24.pl/favicon.ico' unless Site.find_by(name: 'TVN24')
Site.create name: 'Pudelek', site_color: '#F6B1CF', favurl: 'http://www.pudelek.pl/favicon.ico' unless Site.find_by(name: 'Pudelek')
Site.create name: 'Kozaczek', site_color: '#9B164D', favurl: 'http://www.kozaczek.pl/favicon.ico' unless Site.find_by(name: 'Kozaczek')
Site.create name: 'GwiazdyWP', site_color: '#43095D', favurl: 'http://www.wp.pl/favicon.ico' unless Site.find_by(name: 'GwiazdyWP')
Site.create name: 'Stylowi', site_color: '#E6343E', favurl: 'http://stylowi.pl/favicon.ico', have_image: true unless Site.find_by(name: 'Stylowi')
