Site.create name: 'Onet', site_color: '#FFA900', favurl: 'http://www.onet.pl/favicon.ico'
Site.create name: 'Interia', site_color: '#1C3F6F', favurl: 'http://www.interia.pl/favicon.ico'
Site.create name: 'TVN24', site_color: '#00599F', favurl: 'http://www.tvn24.pl/favicon.ico'
Site.create name: 'Pudelek', site_color: '#F6B1CF', favurl: 'http://www.pudelek.pl/favicon.ico'
Site.create name: 'Kozaczek', site_color: '#9B164D', favurl: 'http://www.kozaczek.pl/favicon.ico'
Site.create name: 'GwiazdyWP', site_color: '#43095D', favurl: 'http://www.wp.pl/favicon.ico'
